GUA-220 Build, Push and SAM deploy with Github Actions
alphagov/di-solid-prototype pull request #31
Opened 2022-06-28 14:30 UTC by huwd

2022-06-28 14:53 UTC, alex9smith requested changes
This looks like a good start but I don't think it's quite ready.

> I have a sneaking suspicion i've missed a step that gives Github access to docker to run those commands...

`docker` is already installed on the runner machines, so we get that for free 🎉 

I think you've set  `secrets.GH_ACTIONS_ROLE_ARN` as the ARN for the AWS OIDC provider, but that secret needs to be an ARN for a role so you'll need to add a role definintion to the Cloudformation that allows authentication from the new OIDC provider and has permissions to deploy stuff to ECS, push docker images to ECR etc. There's a starting point in the [Github docs](https://github.com/aws-actions/configure-aws-credentials#sample-iam-role-cloudformation-template) but we'll need to also set the permissions on that role.

2022-06-28 14:53 UTC, alex9smith commented on infrastructure/prototype-app/template.yaml
> +      Tags:
Nice! Is this a standard set of tags we should be using?

2022-06-28 14:53 UTC, alex9smith commented on .github/workflows/build_and_deploy.yaml
> +      - name: Set up SAM cli
```suggestion
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up SAM cli
```

Pretty sure you'll also need a checkout action first to get the latest branch contents

2022-06-28 15:12 UTC, huwd commented on infrastructure/prototype-app/template.yaml
> +      Tags:
I think so.
I wasn't sure what was going on with the ThumbPrint list so I stepped through and verified that was the right hash. Was kinda cool will note below this what I did to prove it.

That URL seems correct.

The rest of the tags are from [here](https://github.com/alphagov/di-devplatform-deploy/blob/main/github-identity/template.yaml). I actually ended up removing two, `Environment` (on the basis we only have one and are not doing build -> integration -> prod for POC), and `System`, which I take to be representing what this is to other parts of DI... again an assumption here that we're less concerned about that 🤔

2022-06-29 14:50 UTC, alex9smith approved these changes
LGTM!  I can't think of a good way of testing this other than merging and hoping, so lets try it🤞🏻

2022-06-29 15:21 UTC, merged